<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\Holiday;
use App\Models\HolidayDefinition;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\Factory;

/** @extends Factory<Holiday> */
class HolidayFactory extends Factory
{
    protected $model = Holiday::class;

    /**
     * Monotonic per-process offset so every generated holiday gets a distinct `date`.
     * `faker->unique()` only tracks values within a single generator instance, so it
     * still collided under `->count(n)` / repeated `create()` calls against the
     * `holidays.date` UNIQUE constraint. Starts in 2030 to stay clear of the 2026/2027
     * dates tests hard-code explicitly.
     */
    private static int $dateSequence = 0;

    public function definition(): array
    {
        return [
            'definition_id' => null,
            'date' => Carbon::parse('2030-01-01')->addDays(self::$dateSequence++)->format('Y-m-d'),
            'name' => $this->faker->words(3, true),
            'type' => null,
            'is_auto_generated' => false,
            'pay_multiplier' => $this->faker->randomElement([2.00, 3.00]),
        ];
    }

    // ── New states ────────────────────────────────────────────────────────────

    public function autoGenerated(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_auto_generated' => true,
        ]);
    }

    public function withDefinition(HolidayDefinition $definition): static
    {
        return $this->state(fn (array $attributes) => [
            'definition_id' => $definition->id,
            'type' => $definition->type,
            'pay_multiplier' => $definition->getEffectivePayMultiplier(),
        ]);
    }
}
