<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\Holiday;
use App\Models\HolidayDefinition;
use Illuminate\Database\Eloquent\Factories\Factory;

/** @extends Factory<Holiday> */
class HolidayFactory extends Factory
{
    protected $model = Holiday::class;

    public function definition(): array
    {
        return [
            'definition_id' => null,
            'date' => $this->faker->unique()->dateTimeBetween('2026-01-01', '2026-12-31')->format('Y-m-d'),
            'name' => $this->faker->words(3, true),
            'type' => null,
            'is_auto_generated' => false,
            'pay_multiplier' => $this->faker->randomElement([2.00, 3.00]),
        ];
    }

    // ── New states ────────────────────────────────────────────────────────────

    public function autoGenerated(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_auto_generated' => true,
        ]);
    }

    public function withDefinition(HolidayDefinition $definition): static
    {
        return $this->state(fn (array $attributes) => [
            'definition_id' => $definition->id,
            'type' => $definition->type,
            'pay_multiplier' => $definition->getEffectivePayMultiplier(),
        ]);
    }
}
