// Inventory Pages - Note: These use named exports from lazy files
// The routes are auto-generated by TanStack Router

export { InventoryLocationsPage } from './locations.lazy'
export { InventoryItemsPage } from './items.lazy'
export { ItemVariantsPage } from './item-variants.lazy'
