/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as UnauthorizedRouteImport } from './pages/unauthorized'
import { Route as StockDashboardRouteImport } from './pages/stock-dashboard'
import { Route as ResetPasswordRouteImport } from './pages/reset-password'
import { Route as LogoutRouteImport } from './pages/logout'
import { Route as LoginRouteImport } from './pages/login'
import { Route as InventoryRouteImport } from './pages/inventory'
import { Route as ForgotPasswordRouteImport } from './pages/forgot-password'
import { Route as EmployeesRouteImport } from './pages/employees'
import { Route as ConfiguracionRouteImport } from './pages/configuracion'
import { Route as CashRouteImport } from './pages/cash'
import { Route as ReportesRouteImport } from './pages/Reportes'
import { Route as ProductosRouteImport } from './pages/Productos'
import { Route as OrdenesRouteImport } from './pages/Ordenes'
import { Route as ClientesRouteImport } from './pages/Clientes'
import { Route as IndexRouteImport } from './pages/index'
import { Route as InventoryIndexRouteImport } from './pages/inventory.index'
import { Route as CashIndexRouteImport } from './pages/cash/index'
import { Route as InventoryLocationsRouteImport } from './pages/inventory/locations'
import { Route as InventoryItemsRouteImport } from './pages/inventory/items'
import { Route as InventoryItemVariantsRouteImport } from './pages/inventory/item-variants'
import { Route as CashTerminalsRouteImport } from './pages/cash/terminals'
import { Route as CashRegistersRouteImport } from './pages/cash/registers'
import { Route as CashBankAccountsRouteImport } from './pages/cash/bank-accounts'
import { Route as AttendanceTodayRouteImport } from './pages/attendance/today'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const StockDashboardRoute = StockDashboardRouteImport.update({
  id: '/stock-dashboard',
  path: '/stock-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/Reportes',
  path: '/Reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/Productos',
  path: '/Productos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdenesRoute = OrdenesRouteImport.update({
  id: '/Ordenes',
  path: '/Ordenes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/Clientes',
  path: '/Clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const CashIndexRoute = CashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CashRoute,
} as any)
const InventoryLocationsRoute = InventoryLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryItemsRoute = InventoryItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryItemVariantsRoute = InventoryItemVariantsRouteImport.update({
  id: '/item-variants',
  path: '/item-variants',
  getParentRoute: () => InventoryRoute,
} as any)
const CashTerminalsRoute = CashTerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => CashRoute,
} as any)
const CashRegistersRoute = CashRegistersRouteImport.update({
  id: '/registers',
  path: '/registers',
  getParentRoute: () => CashRoute,
} as any)
const CashBankAccountsRoute = CashBankAccountsRouteImport.update({
  id: '/bank-accounts',
  path: '/bank-accounts',
  getParentRoute: () => CashRoute,
} as any)
const AttendanceTodayRoute = AttendanceTodayRouteImport.update({
  id: '/attendance/today',
  path: '/attendance/today',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Clientes': typeof ClientesRoute
  '/Ordenes': typeof OrdenesRoute
  '/Productos': typeof ProductosRoute
  '/Reportes': typeof ReportesRoute
  '/cash': typeof CashRouteWithChildren
  '/configuracion': typeof ConfiguracionRoute
  '/employees': typeof EmployeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stock-dashboard': typeof StockDashboardRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/attendance/today': typeof AttendanceTodayRoute
  '/cash/bank-accounts': typeof CashBankAccountsRoute
  '/cash/registers': typeof CashRegistersRoute
  '/cash/terminals': typeof CashTerminalsRoute
  '/inventory/item-variants': typeof InventoryItemVariantsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/locations': typeof InventoryLocationsRoute
  '/cash/': typeof CashIndexRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Clientes': typeof ClientesRoute
  '/Ordenes': typeof OrdenesRoute
  '/Productos': typeof ProductosRoute
  '/Reportes': typeof ReportesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/employees': typeof EmployeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stock-dashboard': typeof StockDashboardRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/attendance/today': typeof AttendanceTodayRoute
  '/cash/bank-accounts': typeof CashBankAccountsRoute
  '/cash/registers': typeof CashRegistersRoute
  '/cash/terminals': typeof CashTerminalsRoute
  '/inventory/item-variants': typeof InventoryItemVariantsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/locations': typeof InventoryLocationsRoute
  '/cash': typeof CashIndexRoute
  '/inventory': typeof InventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Clientes': typeof ClientesRoute
  '/Ordenes': typeof OrdenesRoute
  '/Productos': typeof ProductosRoute
  '/Reportes': typeof ReportesRoute
  '/cash': typeof CashRouteWithChildren
  '/configuracion': typeof ConfiguracionRoute
  '/employees': typeof EmployeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/stock-dashboard': typeof StockDashboardRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/attendance/today': typeof AttendanceTodayRoute
  '/cash/bank-accounts': typeof CashBankAccountsRoute
  '/cash/registers': typeof CashRegistersRoute
  '/cash/terminals': typeof CashTerminalsRoute
  '/inventory/item-variants': typeof InventoryItemVariantsRoute
  '/inventory/items': typeof InventoryItemsRoute
  '/inventory/locations': typeof InventoryLocationsRoute
  '/cash/': typeof CashIndexRoute
  '/inventory/': typeof InventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Clientes'
    | '/Ordenes'
    | '/Productos'
    | '/Reportes'
    | '/cash'
    | '/configuracion'
    | '/employees'
    | '/forgot-password'
    | '/inventory'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/stock-dashboard'
    | '/unauthorized'
    | '/attendance/today'
    | '/cash/bank-accounts'
    | '/cash/registers'
    | '/cash/terminals'
    | '/inventory/item-variants'
    | '/inventory/items'
    | '/inventory/locations'
    | '/cash/'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Clientes'
    | '/Ordenes'
    | '/Productos'
    | '/Reportes'
    | '/configuracion'
    | '/employees'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/stock-dashboard'
    | '/unauthorized'
    | '/attendance/today'
    | '/cash/bank-accounts'
    | '/cash/registers'
    | '/cash/terminals'
    | '/inventory/item-variants'
    | '/inventory/items'
    | '/inventory/locations'
    | '/cash'
    | '/inventory'
  id:
    | '__root__'
    | '/'
    | '/Clientes'
    | '/Ordenes'
    | '/Productos'
    | '/Reportes'
    | '/cash'
    | '/configuracion'
    | '/employees'
    | '/forgot-password'
    | '/inventory'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/stock-dashboard'
    | '/unauthorized'
    | '/attendance/today'
    | '/cash/bank-accounts'
    | '/cash/registers'
    | '/cash/terminals'
    | '/inventory/item-variants'
    | '/inventory/items'
    | '/inventory/locations'
    | '/cash/'
    | '/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  OrdenesRoute: typeof OrdenesRoute
  ProductosRoute: typeof ProductosRoute
  ReportesRoute: typeof ReportesRoute
  CashRoute: typeof CashRouteWithChildren
  ConfiguracionRoute: typeof ConfiguracionRoute
  EmployeesRoute: typeof EmployeesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StockDashboardRoute: typeof StockDashboardRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AttendanceTodayRoute: typeof AttendanceTodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-dashboard': {
      id: '/stock-dashboard'
      path: '/stock-dashboard'
      fullPath: '/stock-dashboard'
      preLoaderRoute: typeof StockDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Reportes': {
      id: '/Reportes'
      path: '/Reportes'
      fullPath: '/Reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Productos': {
      id: '/Productos'
      path: '/Productos'
      fullPath: '/Productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Ordenes': {
      id: '/Ordenes'
      path: '/Ordenes'
      fullPath: '/Ordenes'
      preLoaderRoute: typeof OrdenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Clientes': {
      id: '/Clientes'
      path: '/Clientes'
      fullPath: '/Clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/cash/': {
      id: '/cash/'
      path: '/'
      fullPath: '/cash/'
      preLoaderRoute: typeof CashIndexRouteImport
      parentRoute: typeof CashRoute
    }
    '/inventory/locations': {
      id: '/inventory/locations'
      path: '/locations'
      fullPath: '/inventory/locations'
      preLoaderRoute: typeof InventoryLocationsRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/items': {
      id: '/inventory/items'
      path: '/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof InventoryItemsRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/item-variants': {
      id: '/inventory/item-variants'
      path: '/item-variants'
      fullPath: '/inventory/item-variants'
      preLoaderRoute: typeof InventoryItemVariantsRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/cash/terminals': {
      id: '/cash/terminals'
      path: '/terminals'
      fullPath: '/cash/terminals'
      preLoaderRoute: typeof CashTerminalsRouteImport
      parentRoute: typeof CashRoute
    }
    '/cash/registers': {
      id: '/cash/registers'
      path: '/registers'
      fullPath: '/cash/registers'
      preLoaderRoute: typeof CashRegistersRouteImport
      parentRoute: typeof CashRoute
    }
    '/cash/bank-accounts': {
      id: '/cash/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/cash/bank-accounts'
      preLoaderRoute: typeof CashBankAccountsRouteImport
      parentRoute: typeof CashRoute
    }
    '/attendance/today': {
      id: '/attendance/today'
      path: '/attendance/today'
      fullPath: '/attendance/today'
      preLoaderRoute: typeof AttendanceTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CashRouteChildren {
  CashBankAccountsRoute: typeof CashBankAccountsRoute
  CashRegistersRoute: typeof CashRegistersRoute
  CashTerminalsRoute: typeof CashTerminalsRoute
  CashIndexRoute: typeof CashIndexRoute
}

const CashRouteChildren: CashRouteChildren = {
  CashBankAccountsRoute: CashBankAccountsRoute,
  CashRegistersRoute: CashRegistersRoute,
  CashTerminalsRoute: CashTerminalsRoute,
  CashIndexRoute: CashIndexRoute,
}

const CashRouteWithChildren = CashRoute._addFileChildren(CashRouteChildren)

interface InventoryRouteChildren {
  InventoryItemVariantsRoute: typeof InventoryItemVariantsRoute
  InventoryItemsRoute: typeof InventoryItemsRoute
  InventoryLocationsRoute: typeof InventoryLocationsRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryItemVariantsRoute: InventoryItemVariantsRoute,
  InventoryItemsRoute: InventoryItemsRoute,
  InventoryLocationsRoute: InventoryLocationsRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  OrdenesRoute: OrdenesRoute,
  ProductosRoute: ProductosRoute,
  ReportesRoute: ReportesRoute,
  CashRoute: CashRouteWithChildren,
  ConfiguracionRoute: ConfiguracionRoute,
  EmployeesRoute: EmployeesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InventoryRoute: InventoryRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StockDashboardRoute: StockDashboardRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AttendanceTodayRoute: AttendanceTodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
